//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSVNoiTru.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonDienNuoc
    {
        public int HoaDonDienNuocId { get; set; }
        public string SoHieuPhong { get; set; }
        public string NguoiNopTien { get; set; }
        public int GiaDienId { get; set; }
        public int Chisodiendau { get; set; }
        public int Chisodiencuoi { get; set; }
        public int GiaNuocId { get; set; }
        public int Chisonuocdau { get; set; }
        public int Chisonuoccuoi { get; set; }
        public System.DateTime ThangGhi { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        public virtual GiaDien GiaDien { get; set; }
        public virtual GiaNuoc GiaNuoc { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
