//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSVNoiTru.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonDienNuoc
    {
        public int HoaDonDienNuocId { get; set; }
        public string SoHieuPhong { get; set; }
        public string NguoiNopTien { get; set; }
        public double TienDien { get; set; }
        public double TienNuoc { get; set; }
        public System.DateTime ThangGhi { get; set; }
        public string GhiChu { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string NguoiLap { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
