//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSVNoiTru.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KyTucXa
    {
        public int KyTucXaId { get; set; }
        public string TenKyTucXa { get; set; }
        public string DiaChi { get; set; }
        public string HinhAnh { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
    }
}
