//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSVNoiTru.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MauBieu
    {
        public int MauBieuId { get; set; }
        public int LoaiMauBieuId { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
    
        public virtual LoaiMauBieu LoaiMauBieu { get; set; }
    }
}
