//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSVNoiTru.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongGiaDien
    {
        public int PhongGiaDienId { get; set; }
        public string SoHieuPhong { get; set; }
        public int GiaDienId { get; set; }
        public int Chisodau { get; set; }
        public int Chisocuoi { get; set; }
        public double ThanhTien { get; set; }
        public System.DateTime ThangGhi { get; set; }
        public System.DateTime NgayGhi { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
    
        public virtual GiaDien GiaDien { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
