//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSVNoiTru.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.PhongThietBis = new HashSet<PhongThietBi>();
            this.SinhViens = new HashSet<SinhVien>();
            this.HoaDonDienNuocs = new HashSet<HoaDonDienNuoc>();
        }
    
        public string SoHieuPhong { get; set; }
        public string MaLoaiPhong { get; set; }
        public int TangId { get; set; }
        public int SucChuaToiDa { get; set; }
    
        public virtual LoaiPhong LoaiPhong { get; set; }
        public virtual Tang Tang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhongThietBi> PhongThietBis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinhVien> SinhViens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonDienNuoc> HoaDonDienNuocs { get; set; }
    }
}
