//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSVNoiTru.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVienChuyenPhong
    {
        public int SinhVienChuyenPhongId { get; set; }
        public string MaSinhVien { get; set; }
        public string SoHieuPhongCu { get; set; }
        public string SoHieuPhongMoi { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
    }
}
