//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSVNoiTru.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserQuyen
    {
        public int UserQuyenId { get; set; }
        public int QuyenId { get; set; }
        public string UserName { get; set; }
    
        public virtual Quyen Quyen { get; set; }
        public virtual User User { get; set; }
    }
}
